### PR TITLE
PROTOCOL: Ensure estop change triggers report

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
@keyme/robotics

### CODE REVIEW

**Comment by Jeff-Ciesielski** [comment]
This corrects the issue where releasing the estop button doesn't cause cutter to re-home

**Comment by StephanCoetzee** [comment]
Initialize `sys.last_estop_state` to something known since you check it before you set it the first time.

**Review by StephanCoetzee — COMMENTED** [review]
Initialize `sys.last_estop_state` to something known since you check it before you set it the first time.

**Comment by Jeff-Ciesielski** [comment]
It's global memory, it is implicitly initialized to zero.

**Comment by StephanCoetzee** [comment]
LGTM

**Pull request merged**
