### PR TITLE
PROBING: Fix line number reporting

### PR DESCRIPTION
**Pull request by StephanCoetzee**
Tested - cuts keys and measures keys with https://github.com/keyme/kiosk/pull/9020.

This needs to be merged before https://github.com/keyme/grbl/pull/89.

### CODE REVIEW

**Comment by Jeff-Ciesielski** [comment]
Can you comment a little more about the history behind this?  Just want to make sure that future readers know the reasoning here.

**Comment by StephanCoetzee** [comment]
Sure. The correct line number reporting is important because callbacks get registered and called in motion based on line numbers.

There is a special line number in motion used for probing, namely `0x4000`. This line number needs to be reported to motion once a probe is finished. `0x4000`, however, cannot be sent in the N portion of a Gcode command - it purposely exceeds the maximum line number that Grbl supports since `0x4000` is reserved as a special line number.

In motion, a callback gets registered on the normal (i.e. not special), generated line number. Motion, however, also relies on the special line number being reported. This PR addresses the issue of reporting the special probe line number, namely `0x4000`.

**Comment by Jeff-Ciesielski** [comment]
LGTM

**Comment by StephanCoetzee** [comment]
@mdicicco

**Comment by mdicicco** [comment]
:+1:

**Pull request merged**
