### PR TITLE
SYSTEM: Re-purpose '$B' command for disengaging motors manually

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
Also: Roll version to 0.4.6

Tested on the kiosk.

@knitHacker

### CODE REVIEW

**Comment by Jeff-Ciesielski** [comment]
Also, FWIW: We don't currently use the $B command anywhere else, so this is no chance this will break something else

**Comment by zsalzbank** [comment]
What if I was using it? :)

**Comment by Jeff-Ciesielski** [comment]
Should've forked man :)

**Comment by knitHacker** [comment]
Was this not working as is? Couldn't we use the old code and just sent all motors from MOTION?

**Comment by Jeff-Ciesielski** [comment]
It was doing something else entirely.

**Comment by knitHacker** [comment]
LGTM

**Pull request merged**
