### PR TITLE
Added ability to enable/disable encoder with $e1/$e0

### PR DESCRIPTION
**Pull request by ashelly**
default is disabled.

### CODE REVIEW

**Comment by penguinland** [comment]
...so how do I enable the gripper encoder?

**Comment by mdicicco** [comment]
This is the GRBL half.  Don't worry about this.  There will be a motion piece that will give you an IPC command to toggle this code.

**Comment by penguinland** [comment]
Good point.

**Comment by ashelly** [comment]
good point.  I was just going to tell Alan to send a '$e1', but he can't do that directly.  Working on it.

**Pull request merged**
