### PR TITLE
Fix handling of `M` commands in gcode parser

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
With the upcoming ability to load large sections of gcode, we could
theoretically upload the entire program in the form:
(Home=>Select Key=>Grab=>bump=>Position=>Cut=>Release) with an `M00` in
between each state, allowing the cutter to simply issue a continue
command in between stages after validating that they were successful.

### CODE REVIEW

**Comment by mdicicco** [comment]
heh.  Is a bug in the main grbl implementation or just a design choice that they made?

**Comment by Jeff-Ciesielski** [comment]
I think it's just a bug in their parser.

**Comment by kborer** [comment]
send it upstream

**Comment by Jeff-Ciesielski** [comment]
@kborer : Looks to be fixed upstream.  In fact, their fix also included a few other lines, I think we should revert this and fix it the same way they did.

**Comment by mdicicco** [comment]
Do you want me to revert that PR or do you want to just make a new PR that fixes it the other way?

**Comment by Jeff-Ciesielski** [comment]
I'll just make anther PR.  Going to see if they have any other upstream parser improvements that can be easily incorporated.

**Pull request merged**
