### PR TITLE
VERSION: Roll to 0.3.9

### PR DESCRIPTION
**Pull request by StephanCoetzee**

### CODE REVIEW

**Comment by StephanCoetzee** [comment]
Command line stepper should be updated first. Closing this PR for now.

**Comment by StephanCoetzee** [comment]
After a discussion this morning we decided to reopen this PR without fixing command line stepper first. Fixing command line stepper will make the dependency situation with https://github.com/keyme/kiosk/pull/9020 worse.

https://github.com/keyme/kiosk/pull/9020 requires this roll-over to 3.9.
Command line stepper requires https://github.com/keyme/kiosk/pull/9020
If this 3.9 change requires the new command line stepper, we have a circular dependency situation.

We are going to merge Grbl 3.9, check the hex file into https://github.com/keyme/kiosk/pull/9020 and merge https://github.com/keyme/kiosk/pull/9020. A single function in command line stepper (probing) is going to be broken for a very short while before the command line stepper fix gets merged.

@Jeff-Ciesielski

**Comment by Jeff-Ciesielski** [comment]
LGTM

**Comment by StephanCoetzee** [comment]
Requires - https://github.com/keyme/grbl/pull/90

**Comment by Jeff-Ciesielski** [comment]
Ok, I think we're good to go here.  LGTM.  Lets get this party started.

**Pull request merged**
